export const FETCH_TRENDING_MOVIES_REQUEST = 'FETCH_TRENDING_MOVIES_REQUEST';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export const FETCH_TRENDING_MOVIES_FAILED = 'FETCH_TRENDING_MOVIES_FAILED';